### ISSUE TITLE
Callback parameter missing from `fs.writeFile` call.

### ISSUE THREAD

**Issue by MicahZoltu** [NethermindEth/nethermind.launcher#16]
https://github.com/NethermindEth/nethermind.launcher/blob/75e7b31d69c26410e7c863422c5d47cd6aac9726/index.js#L214
https://github.com/NethermindEth/nethermind.launcher/blob/75e7b31d69c26410e7c863422c5d47cd6aac9726/index.js#L262

Both of these should have a 4th callback parameter that contains the code you wish to execute after the write completes.  In the first case, you *may* just want `() => {}` since it doesn't appear anything else interesting happens, so the file write can succeed or fail in the background.  In the second case, I suspect you want the `startProcess` line to occur inside the callback.

Note: On newish versions of NodeJS you can do this instead, which I recommend:
```js
const fs = require('fs/promises')
async function main() {
    ...
    await fs.writeFile(path, data, 'utf-8')
    ...
}
```

**Comment by matilote** [comment]
fixed with pr #17
